CREATE TABLE EMP_CURSOR
AS SELECT * FROM EMP;

ALTER TABLE EMP_CURSOR
MODIFY EMPNO NUMBER CONSTRAINT EMP_CURSOR_PK PRIMARY KEY;

ALTER TABLE EMP_CURSOR
DROP CONSTRAINT EMP_CURSOR_PK;

SELECT * FROM EMP WHERE DEPTNO=10;
SELECT * FROM EMP_CURSOR;

CALL PROC_AURG('ю╞еба╬');

UPDATE EMP_CURSOR
SET EMPNO=7701
WHERE EMPNO=7702;

 SELECT COUNT(*) FROM EMP WHERE SAL>2500;