 CREATE TABLE USERS (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(50) ,
    NICKNAME VARCHAR2(50),
    POINT NUMBER DEFAULT 0,
    PHONE VARCHAR2(20) ,
    RATING VARCHAR2(50) DEFAULT 0,
    ROLE VARCHAR2(20) DEFAULT 'ROLE_USER'
);
    
    -- 유저 번호 자동증가    
    CREATE SEQUENCE USER_ID_SEQ
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 99999999999
       NOCYCLE
       NOCACHE
       NOORDER;
 
COMMIT;

--연습용
CREATE TABLE TEST_BOARD(
    ID NUMBER(10) PRIMARY KEY,
    REG_TIME DATE,
    UPDATE_TIME DATE,
    CREATED_BY VARCHAR2(8) NOT NULL,
    MODIFIED_BY VARCHAR2(20) NOT NULL,
    ITEM_DETAIL VARCHAR2(100) NOT NULL,
    ITEM_NAME VARCHAR2(20) NOT NULL,
    ITEM_SELL_STATUS VARCHAR2(10) NOT NULL,
    PRICE NUMBER(20) NOT NULL,
    STOCK NUMBER(20) NOT NULL
);

CREATE SEQUENCE TEST_BOARD_SEQ;

