CREATE TABLE MEMBER(
    ID VARCHAR2(10) CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
    PW VARCHAR2(10) CONSTRAINT MEMBER_PW_NN NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE BOARD(
    NUM NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    ID VARCHAR2(10) NOT NULL,
    POSTDATE DATE DEFAULT SYSDATE NOT NULL,
    VISITCOUNT NUMBER(6)
);

ALTER TABLE BOARD
ADD CONSTRAINT BOARD_FK_MEMBER FOREIGN KEY(ID) REFERENCES MEMBER(ID);

CREATE SEQUENCE SEQ_BOARD_NUM
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;
    
INSERT INTO MEMBER(ID,PW,NAME) VALUES('YOO','1234','태종');   
INSERT INTO BOARD(NUM,TITLE,CONTENT,ID,VISITCOUNT) 
VALUES(SEQ_BOARD_NUM.NEXTVAL,'제목0','내용0','YOO',0);

drop sequence SEQ_BOARD_NUM;
    