CREATE TABLE ACCOUNTS (
    ID VARCHAR2(10) PRIMARY KEY,
    PW VARCHAR2(20)  
);

INSERT INTO ACCOUNTS
VALUES ('TEST1','1234');

SELECT * FROM ACCOUNTS;

CREATE TABLE BASIC_BBS (
    ID NUMBER(4) PRIMARY KEY,
    WRITER VARCHAR2(30),
    TITLE VARCHAR2(100),
    CONTENT VARCHAR2(1000)
);

CREATE SEQUENCE BASIC_BBS_SEQ;

SELECT * FROM BASIC_BBS;

