CREATE TABLE REGIONS(
    RE_NUM NUMBER(4) PRIMARY KEY,
    RE_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE MEMBERS (
    ME_NUM NUMBER(4) CONSTRAINT ME_PK_NUM PRIMARY KEY,
    ME_ID VARCHAR2(30) NOT NULL UNIQUE,
    ME_PASS VARCHAR2(60) NOT NULL,
    ME_NAME VARCHAR2(30) NOT NULL,
    ME_BIRTH VARCHAR2(30) NOT NULL,
    ME_SEX VARCHAR2(30) NOT NULL,
    ME_AGE NUMBER(3) NOT NULL,
    ME_PHONE VARCHAR2(30) NOT NULL UNIQUE,
    ME_EMAIL VARCHAR2(60) NOT NULL UNIQUE,
    ME_KAKAO VARCHAR2(30) NOT NULL,
    RE_NUM NUMBER(4) CONSTRAINT ME_FK_NUM REFERENCES REGIONS(RE_NUM)
);
CREATE TABLE  PETINFOS(
    PE_NUM NUMBER(4) CONSTRAINT PK_PE_NUM PRIMARY KEY,
    PE_KIND VARCHAR2(30) NOT NULL,
    PE_SEX VARCHAR2(30) NOT NULL,
    PE_SIZE VARCHAR2(30) NOT NULL,
    PE_NAME VARCHAR2(30) NOT NULL,
    PE_OPIC VARCHAR2(30) NOT NULL,
    PE_NPIC VARCHAR2(30) NOT NULL,
    PE_INTRO VARCHAR2(30),
    ME_NUM NUMBER(4) CONSTRAINT FK_ME_NUM REFERENCES MEMBERS(ME_NUM)
);

CREATE TABLE MEMINFOS(
     ME_NUM NUMBER(4) 
    ,IN_HEIGHT NUMBER(3) NOT NULL
    ,IN_STYLE VARCHAR2(30) NOT NULL
    ,IN_EDU VARCHAR2(30) NOT NULL
    ,IN_RLG VARCHAR2(30) NOT NULL
    ,IN_DRUNK VARCHAR2(30) NOT NULL
    ,IN_SMOKE VARCHAR2(30) NOT NULL
    ,IN_CHAR VARCHAR2(30) NOT NULL
    ,IN_MBTI VARCHAR2(30) NOT NULL
    ,IN_HOBBY VARCHAR2(30) NOT NULL
    ,IN_JOB VARCHAR2(30) NOT NULL
    ,IN_HASPET VARCHAR(6) NOT NULL
    ,IN_OPIC VARCHAR2(60) NOT NULL
    ,IN_NPIC VARCHAR2(60) NOT NULL
    ,IN_OVOICE VARCHAR2(60) NOT NULL
    ,IN_NVOICE VARCHAR2(60) NOT NULL
    ,PE_NUM NUMBER(4) 
    ,CONSTRAINT FK_ME_IN_NUM FOREIGN KEY(ME_NUM) REFERENCES MEMBERS(ME_NUM)
    ,CONSTRAINT FK_PE_IN_NUM FOREIGN KEY(PE_NUM) REFERENCES PETINFOS(PE_NUM)
);


CREATE TABLE MATCHINGS(
    ME_NUM NUMBER(4) CONSTRAINT FK_ME_MAT_NUM REFERENCES MEMBERS(ME_NUM),
    MA_MESS VARCHAR2(300) NOT NULL
);

CREATE TABLE QNAS(
    QA_NUM NUMBER(4) PRIMARY KEY,
    QA_NAME VARCHAR2 (30) NOT NULL,
    QA_CONTENT VARCHAR2 (300) NOT NULL,
    QA_OFILE  VARCHAR2 (300), 
    QA_NFILE VARCHAR2 (300),
    ME_NUM NUMBER(4) CONSTRAINT FK_ME_QNA_NUM REFERENCES MEMBERS(ME_NUM),
    QA_POSTDATE DATE DEFAULT SYSDATE,
    QA_PASS VARCHAR2 (30)   
);

CREATE TABLE REVIEWS  (
    RV_NUM NUMBER(4) CONSTRAINT PK_RV_NUM PRIMARY KEY,
    RV_NAME VARCHAR2(30) NOT NULL,
    RV_CONTENT VARCHAR2(300) NOT NULL,
    RV_STAR NUMBER(4) NOT NULL,
    RV_OFILE VARCHAR2(300),
    RV_NFILE VARCHAR2(300),
    ME_NUM NUMBER(4) CONSTRAINT FK_ME_REV_NUM REFERENCES MEMBERS(ME_NUM),
    RV_POSTDATE DATE DEFAULT SYSDATE,
    RV_PASS VARCHAR2(30) NOT NULL
);


drop table QNAS;
drop table REVIEWS;

CREATE SEQUENCE SEQ_REVIEWSBOARD_NUM
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1
    NOMAXVALUE
    NOCYCLE
    NOCACHE;
    
insert into REVIEWS (RV_NUM,RV_NAME,RV_CONTENT,RV_STAR,RV_PASS)
    values (SEQ_REVIEWSBOARD_NUM.nextval,'리뷰 제목5 입니다.','리뷰내용',5,'1234');

commit;

CREATE SEQUENCE ME_SEQ
INCREMENT BY 1
START WITH 101
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE RE_SEQ
INCREMENT BY 1
START WITH 226
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE PE_SEQ
INCREMENT BY 1
START WITH 401
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE QNA_SEQ
INCREMENT BY 1
START WITH 501
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE REV_SEQ
INCREMENT BY 1
START WITH 601
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;


select last_number from user_sequences where sequence_name='REV_SEQ';


SELECT ROWNUM, S.*
FROM ( SELECT R.*
        FROM REVIEWS R
        WHERE R.RV_STAR>3
        ORDER BY R.RV_STAR DESC, RV_POSTDATE DESC) S
WHERE ROWNUM<4;

SELECT R.*, M.ME_NUM, M.ME_NAME 
        FROM REVIEWS R, MEMBERS M
        WHERE R.ME_NUM = M.ME_NUM
        AND M.ME_NUM=161
        AND R.RV_NUM=624;







