SELECT EMPNO, ENAME
    ,FN_GET_DEPT_NAME(DEPTNO) AS DEPARTMENT_NAME
FROM EMP;

CREATE TABLE PKGTEST(
    PNAME VARCHAR2(20),
    AGE NUMBER(3),
    GENDER VARCHAR2(10)
);
DESC PKGTEST;

SELECT *
FROM PKGTEST;

TRUNCATE TABLE PKGTEST;

SELECT PKG1.PARSEGENDER('S') FROM DUAL;
    
  