/*UPDATE

    UPDATE TB
    SET COL1=VAL1, COL2=VAL2, ...
    WHERE CON;
    
    INSERT
    
    INSERT INTO TB (COL1, COL2,...)
    VALUES (VAL1,VAL2,VAL3...)
    
    DELETE
    
    DELETE FROM TB WHERE CON;
    
    GROUP BY
    
    SELECT COLS (COUNT MAX MIN SUM AVG)
    FROM TB
    WHERE CONDITION
    GROUP BY COLS
    
    HAVING
    
    SELECT COL
    FROM TB
    WHERE CON
    GROUP BY COLS
    HAVING CON
    ORDER BY COL
    
    제작하는 회사를 벤더라고 한다
    
    JOIN
    
    SELECT COLS
    FROM TB1
    FULL(INNER, RIGHT, LEFT) OUTER JOIN TB2
    ON CON
    
    SELF JOIN
    SELECT COLS
    FROM TB1
    FULL(INNER, RIGHT, LEFT) OUTER JOIN TB1
    ON CON
    
    SUB QUERY 서브쿼리
    SELECT 절/ FROM 절/ WHERE 절(IN, ALL, ANY)
    
    WITH
    
    E10 AS (SELECT * FROM EMP WHERE DEPTNO=10).
    D AS (SELECT * FROM DEPT)
    SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
    FROM E10, D
    WHERE E10.DEPTNO=D.DEPTNO;
    
    SELECT E10.EMPNO, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
    FROM (SELECT * FROM EMP WHERE DEPTNO=10) E10
        ,(SELECT * FROM DEPT) D
        WHERE E10.DEPTNO=D.DEPTNO;
        
    DDL
    제약 조건(CONSTRAINT)
    1. NOT NULL
    2. UNIQUE
    3. PRIMARY KEY
    4. FOREIGN KEY
    5. DEFAULT
    
    
*/

--5장 Q1

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE ENAME LIKE '%S'
;

--Q2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=30
    AND JOB='SALESMAN'
;

--Q3
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO IN(20,30)
    AND SAL>2000
;

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=20
    AND SAL>2000
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=30
    AND SAL>2000
;

--Q4
SELECT *
FROM EMP
WHERE SAL<2000
 OR SAL>3000
;

SELECT *
FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

--Q5
SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE ENAME LIKE '%E%'
    AND DEPTNO=30
    AND SAL NOT BETWEEN 1000 AND 2000; 

--Q6
SELECT * 
FROM EMP
WHERE COMM IS NULL
    AND MGR IS NOT NULL
    AND JOB IN('MANAGER','CLERK')
    AND ENAME NOT LIKE '_L%'
;

--6장 Q1
SELECT EMPNO
    , RPAD(SUBSTR(EMPNO,1,2),LENGTH(EMPNO),'*') AS MASKING_EMPNO
    , ENAME
    , RPAD(SUBSTR(ENAME,1,1),LENGTH(ENAME),'*') MASKING_ENAME
FROM EMP
WHERE LENGTH(ENAME)>=5 AND LENGTH(ENAME)<6;

--Q2
SELECT EMPNO, ENAME, SAL
    , TRUNC(SAL/21.5,2) DAY_PAY
    , ROUND(SAL/21.5/8,1) TIME_PAY
FROM EMP;

--Q3
SELECT EMPNO, ENAME
    ,TO_CHAR(HIREDATE,'YYYY/MM/DD') HIREDATE
    ,TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3),'월요일'),'YYYY-MM-DD')R_JOB
    ,NVL(TO_CHAR(COMM), 'N/A') COMM
FROM EMP;

--Q4




