SELECT EMPNO, ENAME, JOB, MGR,HIREDATE,SAL,COMM,DEPTNO
FROM EMP
WHERE ENAME LIKE '%S';

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=30
    AND JOB='SALESMAN';
    
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO IN(20,30)
    AND SAL>2000;
    
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO =20
    AND SAL>2000
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO =30
    AND SAL>2000;
    
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE SAL<2000 OR SAL>3000;

SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE ENAME LIKE '%E%'
    AND DEPTNO=30
    AND SAL NOT BETWEEN 1000 AND 2000
    ;
    
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE COMM IS NULL
    AND MGR IS NOT NULL
    AND JOB IN('MANAGER', 'CLERK')
    AND ENAME NOT LIKE '_L%';

SELECT EMPNO
    , RPAD(SUBSTR(EMPNO,1,2),LENGTH(EMPNO),'*') AS MASKING_EMPNO
    , ENAME
    , RPAD(SUBSTR(ENAME,1,1),LENGTH(ENAME),'*') AS MASKING_ENAME
FROM EMP
WHERE LENGTH(ENAME)>=5
    AND LENGTH(ENAME)<6;
    
SELECT EMPNO, ENAME, SAL
    , TRUNC(SAL/21.5,2) AS DAY_PAY
    , ROUND(SAL/21.5/8,1) AS TIME_PAY
FROM EMP;

SELECT EMPNO, ENAME
    , TO_CHAR(HIREDATE,'YYYY/MM/DD') AS HIREDATE
    , TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE,3),'¿ù¿äÀÏ'),'YYYY-MM-DD') AS R_JOB
    , NVL(TO_CHAR(COMM),'N/A') AS COMM
FROM EMP;

SELECT EMPNO, ENAME, MGR
    , CASE
        WHEN MGR IS NULL THEN '0000'
        WHEN SUBSTR(MGR,1,2)=75 THEN '5555'
        WHEN SUBSTR(MGR,1,2)=76 THEN '6666'
        WHEN SUBSTR(MGR,1,2)=77 THEN '7777'
        WHEN SUBSTR(MGR,1,2)=78 THEN '8888'
        ELSE TO_CHAR(MGR)
        END AS CHG_MGR
FROM EMP;

SELECT DEPTNO
    ,TRUNC(AVG(SAL)) AVG_SAL
    ,MAX(SAL) MAX_SAL
    ,MIN(SAL) MIN_SAL
    ,COUNT(*) CNT
FROM EMP 
GROUP BY DEPTNO
;

SELECT JOB, COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(JOB)>=3;

SELECT TO_CHAR(HIREDATE,'YYYY') HIRE_YEAR, DEPTNO, COUNT(*) CNT
FROM EMP
WHERE TO_CHAR(HIREDATE,'YYYY') IS NOT NULL
GROUP BY TO_CHAR(HIREDATE,'YYYY'),DEPTNO ;

SELECT NVL2(COMM,'O','X') EXIST_COMM, COUNT(*) CNT
FROM EMP
GROUP BY NVL2(COMM,'O','X');

SELECT DEPTNO
    , TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR
    , COUNT(*) CNT
    , MAX(SAL) MAX_SAL
    , SUM(SAL) SUM_SAL
    , AVG(SAL) AVG_SAL
FROM EMP
WHERE DEPTNO IS NOT NULL
AND TO_CHAR(HIREDATE, 'YYYY') IS NOT NULL
GROUP BY DEPTNO, TO_CHAR(HIREDATE, 'YYYY')
;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
AND 
E.SAL>2000
ORDER BY DEPTNO, SAL;

SELECT D.DEPTNO, D.DNAME, TRUNC(AVG(SAL)) AVG_SAL, MAX(SAL) MAX_SAL, MIN(SAL) MIN_SAL, COUNT(*) CNT
FROM DEPT D, EMP E
WHERE D.DEPTNO=E.DEPTNO
GROUP BY D.DEPTNO, D.DNAME
;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM DEPT D, EMP E
WHERE D.DEPTNO=E.DEPTNO
ORDER BY D.DEPTNO, D.DNAME;

SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL, D.DEPTNO, S.LOSAL, S.HISAL, S.GRADE
    , M.EMPNO AS MGR_EMPNO
    , M.ENAME AS MGR_ENAME
FROM EMP E, DEPT D,SALGRADE S, EMP M
WHERE E.DEPTNO=D.DEPTNO(+)
    AND E.MGR=M.EMPNO(+)
    AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
ORDER BY D.DEPTNO, E.EMPNO;

SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
AND JOB IN(SELECT JOB
            FROM EMP
            WHERE ENAME='ALLEN');
            
SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL, S.GRADE
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO=D.DEPTNO 
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
AND E.SAL>(SELECT AVG(SAL)
            FROM EMP)
            ORDER BY E.SAL DESC, E.EMPNO;
            
SELECT E.EMPNO, E.ENAME, E.JOB, D.DEPTNO ,D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
AND D.DEPTNO=10
AND JOB NOT IN(SELECT JOB
                FROM EMP
                WHERE DEPTNO=30);
                
                
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND SAL>(SELECT MAX(SAL)
        FROM EMP
        WHERE JOB='SALESMAN')
        ORDER BY EMPNO;
        
INSERT INTO CH10_DEPT VALUES (90,'DDL','HONG');
                
                
                
                
                
                
                
                