--Q1
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE ENAME LIKE '%S';

--Q2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP 
WHERE DEPTNO=30
    AND JOB='SALESMAN';
    
--Q3
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO IN(20,30)
    AND SAL>2000;
    
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=20
    AND SAL>2000
    UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=30
    AND SAL>2000;
    
    
--Q4
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE SAL<2000 
    OR SAL>3000;

--Q5
SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE ENAME LIKE '%E%'
    AND DEPTNO=30
    AND SAL NOT BETWEEN 1000 AND 2000
ORDER BY ENAME, EMPNO, SAL; 

--Q6
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE COMM IS NULL
    AND MGR IS NOT NULL
    AND JOB IN('MANAGER','CLERK')
    AND ENAME NOT LIKE '_L%';

--Q1
SELECT EMPNO
    , RPAD(SUBSTR(EMPNO,1,2),LENGTH(EMPNO),'*') AS MASKING_EMPNO
    , ENAME
    , RPAD(SUBSTR(ENAME,1,1),LENGTH(ENAME),'*') AS MASKING_ENAME
FROM EMP
WHERE LENGTH(ENAME)>=5
    AND LENGTH(ENAME)<6;


--Q2
SELECT EMPNO
    , ENAME
    , SAL
    , TRUNC(SAL/21.5,2) DAY_PAY
    , ROUND(SAL/21.5/8,1) TIME_PAY
FROM EMP;

--Q3
SELECT EMPNO
    , ENAME
    , TO_CHAR(HIREDATE,'YYYY/MM/DD') AS HIREDATE
    , TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE,3),'¿ù¿äÀÏ'),'YYYY-MM-DD') AS R_JOB
    , NVL(TO_CHAR(COMM),'N/A') AS COMM
FROM EMP;

--Q4
SELECT EMPNO
    , ENAME
    , MGR
    , CASE
        WHEN MGR IN NULL THEN '0000'
        WHEN SUBSTR(MGR,1,2)=75 THEN '5555'
        WHEN SUBSTR(MGR,1,2)=76 THEN '6666'
        WHEN SUBSTR(MGR,1,2)=77 THEN '7777'
        WHEN SUBSTR(MGR,1,2)=76 THEN '8888'
        ELSE TO_CHAR(MGR)
        END AS CHG_MGR
FROM EMP;

--Q1
SELECT DEPTNO
    , TRUNC(AVG(SAL)) AS AVG_SAL
    , MAX(SAL) AS MAX_SAL
    , MIN(SAL) AS MIN_SAL
    , COUNT(*) AS CNT
FROM EMP
GROUP BY DEPTNO;

--Q2
SELECT JOB
    , COUNT(*)
FROM EMP
GROUP BY JOB
HAVING COUNT(JOB)>=3;

--Q3
SELECT TO_CHAR(HIREDATE,'YYYY') AS HIRE_YEAR
    , DEPTNO
    , COUNT(*) AS CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YYYY'), DEPTNO;
    
--Q4
SELECT NVL2(COMM,'O','X') AS EXIST_COMM
    ,COUNT(*) AS CNT
FROM EMP
GROUP BY NVL2(COMM,'O','X');


--Q5
SELECT DEPTNO
    , TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR
    , COUNT(*) AS CNT
    , MAX(SAL) AS MAX_SAL
    , SUM(SAL) AS SUM_SAL
    , AVG(SAL) AS AVG_SAL
FROM EMP
GROUP BY DEPTNO, TO_CHAR(HIREDATE, 'YYYY');

--Q1
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
    AND E.SAL>2000;

--Q2
SELECT D.DEPTNO, D.DNAME
    , TRUNC(AVG(SAL)) AS AVG_SAL
    , MAX(SAL) AS MAX_SAL
    , MIN(SAL) AS MIN_SAL
    , COUNT(*) AS CNT
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;

--Q3
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.JOB, E.SAL
FROM EMP E, DEPT D
WHERE D.DEPTNO=E.DEPTNO
ORDER BY D.DEPTNO, E.ENAME
;

--Q4
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME
    , NVL(TO_CHAR(E.MGR), ' ') MGR
    , E.SAL
    , D.DEPTNO
    , S.LOSAL, S.HISAL, S.GRADE
    , NVL(TO_CHAR(E1.EMPNO),' ') AS MGR_EMPNO
    , NVL(E1.ENAME,' ') AS MGR_ENAME
FROM EMP E, EMP E1, DEPT D, SALGRADE S
WHERE E.DEPTNO(+)=D.DEPTNO
    AND E.MGR=E1.EMPNO(+)
    AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
ORDER BY D.DEPTNO, E.EMPNO;

--Q1
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
    AND JOB IN(SELECT JOB
                FROM EMP
                WHERE ENAME='ALLEN')
                ORDER BY SAL DESC; 

--Q2
SELECT E.EMPNO, E.ENAME, D.DNAME, TO_CHAR(E.HIREDATE,'YYYY-MM-DD') AS HIREDATE
    , D.LOC, E.SAL, S.GRADE
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO=D.DEPTNO
    AND SAL>(SELECT AVG(SAL)
            FROM EMP)
    AND E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY E.SAL DESC, E.EMPNO;

--Q3
SELECT E.EMPNO, E.ENAME, E.JOB, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
    AND D.DEPTNO=10
    AND JOB NOT IN(SELECT DISTINCT JOB
                    FROM EMP
                    WHERE DEPTNO=30);

--Q4
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E, SALGRADE S
WHERE SAL>(SELECT MAX(SAL)
    FROM EMP
    WHERE JOB='SALESMAN')
    AND E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY E.EMPNO;

SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE
FROM EMP E, SALGRADE S
WHERE SAL>ALL(SELECT DISTINCT SAL
    FROM EMP
    WHERE JOB='SALESMAN')
    AND E.SAL BETWEEN S.LOSAL AND S.HISAL
ORDER BY EMPNO;


--Q1
    CREATE TABLE CH11_EMP AS SELECT * FROM EMP;
    CREATE TABLE CH11_DEPT AS SELECT * FROM DEPT;
    CREATE TABLE CH11_SALGRADE AS SELECT * FROM SALGRADE;
    
    INSERT INTO CH11_DEPT(DEPTNO,DNAME,LOC) VALUES (50, 'ORACLE', 'BUSAN');
    INSERT ALL
        INTO CH11_DEPT VALUES (60, 'SQL', 'ILSAN')
        INTO CH11_DEPT VALUES (70, 'SELECT', 'INCHEON')
        INTO CH11_DEPT VALUES (80, 'DML', 'BUNDANG')
    SELECT * FROM DUAL;
    
    DELETE FROM CH11_DEPT WHERE DEPTNO=50;
    SELECT *FROM CH11_DEPT;
    
    ALTER TABLE CH11_DEPT
    MODIFY DEPTNO NUMBER CONSTRAINT PK_DEPTNO1 PRIMARY KEY;

    ALTER TABLE CH11_DEPT
    DROP CONSTRAINT PK_DEPTNO1;
    
    ALTER TABLE CH11_EMP
    MODIFY EMPNO NUMBER CONSTRAINT PK_EMPNO1 PRIMARY KEY;
    
--Q2
    INSERT ALL
        INTO CH11_EMP VALUES (7201,'TEST_USER1','MANAGER',7788,TO_DATE('2016-01-02','YYYY-MM-DD'),4500,NULL,50)
        INTO CH11_EMP VALUES (7202,'TEST_USER2','CLERK',7201,TO_DATE('2016-02-21','YYYY-MM-DD'),1800,NULL,50)
        INTO CH11_EMP VALUES (7203,'TEST_USER3','ANALYST',7201,TO_DATE('2016-04-11','YYYY-MM-DD'),3400,NULL,60)
        INTO CH11_EMP VALUES (7204,'TEST_USER4','SALESMAN',7201,TO_DATE('2016-05-31','YYYY-MM-DD'),2700,300,60)
        INTO CH11_EMP VALUES (7205,'TEST_USER5','CLERK',7201,TO_DATE('2016-07-20','YYYY-MM-DD'),2600,NULL,70)
        INTO CH11_EMP VALUES (7206,'TEST_USER6','CLERK',7201,TO_DATE('2016-09-08','YYYY-MM-DD'),2600,NULL,70)
        INTO CH11_EMP VALUES (7207,'TEST_USER7','LECTURER',7201,TO_DATE('2016-10-28','YYYY-MM-DD'),2300,NULL,80)
        INTO CH11_EMP VALUES (7208,'TEST_USER8','STUDENT',7201,TO_DATE('2018-03-09','YYYY-MM-DD'),1200,NULL,80)
    SELECT * FROM DUAL;
    
--Q3
    UPDATE CH11_EMP
    SET DEPTNO=70
    WHERE SAL>(SELECT AVG(SAL)
                FROM CH11_EMP
                WHERE DEPTNO=50 );
                
    SELECT * FROM CH11_EMP;
    SELECT * FROM EMP;
   DROP TABLE CH11_EMP;
   
--Q4
 UPDATE CH11_EMP
 SET SAL=SAL*1.1, DEPTNO=80
 WHERE HIREDATE>(SELECT MIN(HIREDATE)
                FROM  CH11_EMP
                WHERE DEPTNO=60);
 SELECT * FROM CH11_EMP;               
                
--Q5
DELETE FROM CH11_EMP
WHERE EMPNO IN(SELECT EMPNO
        FROM CH11_EMP, CH11_SALGRADE
        WHERE SAL BETWEEN LOSAL AND HISAL
            AND GRADE=5);
    
SELECT * FROM CH11_EMP;   

--Q11
SELECT * FROM DEPT;

--Q1
CREATE TABLE EMP_HW1(
    EMPNO NUMBER(4),
    ENAME VARCHAR(10),
    JOB VARCHAR(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
)

DESC EMP_HW1;
SELECT * FROM EMP_HW1;

--Q2
ALTER TABLE EMP_HW1
ADD BIGO VARCHAR(20);

--Q3
ALTER TABLE EMP_HW1
MODIFY BIGO VARCHAR(30);

--Q4
ALTER TABLE EMP_HW1
RENAME COLUMN BIGO TO REMARK;

--Q5
SELECT * FROM EMP_HW1;
SELECT * FROM EMP;

INSERT INTO EMP_HW1(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
SELECT *
FROM EMP;

--Q6
DROP TABLE EMP_HW1;

--Q1
CREATE TABLE EMPIDX
AS SELECT * FROM EMP;

CREATE INDEX IDX_EMPIDX_EMPNO
ON EMPIDX(EMPNO);

SELECT * FROM USER_INDEXES
WHERE INDEX_NAME='IDX_EMPIDX_EMPNO';

--Q2
CREATE OR REPLACE VIEW EMPIDX_OVER15K
AS (SELECT EMPNO, ENAME, JOB, DEPTNO, SAL
    ,NVL2(COMM,'O','X') AS COMM 
FROM EMPIDX 
WHERE SAL>1500);

SELECT * FROM EMPIDX_OVER15K;

--Q3
DROP TABLE DEPTSEQ;
CREATE TABLE DEPTSEQ
AS SELECT * FROM DEPT;

DROP SEQUENCE SEQ_DEPTSEQ;
CREATE SEQUENCE SEQ_DEPTSEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99
    MINVALUE 1
    NOCYCLE
    NOCACHE;
    
    INSERT INTO DEPTSEQ VALUES (SEQ_DEPTSEQ.NEXTVAL,'DATABASE','SEOUL');
    INSERT INTO DEPTSEQ VALUES (SEQ_DEPTSEQ.NEXTVAL,'WEB','BUSAN');
    INSERT INTO DEPTSEQ VALUES (SEQ_DEPTSEQ.NEXTVAL,'MOBILE','ILSAN');
    
SELECT * FROM DEPTSEQ;
SELECT SEQ_DEPTSEQ.CURRVAL FROM DUAL;

--Q14
DROP TABLE DEPT_CONST;
CREATE TABLE DEPT_CONST2(
    DEPTNO NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK2 PRIMARY KEY,
    DNAME VARCHAR(14) CONSTRAINT DEPTCONST_DNAME_UNQ2 UNIQUE,
    LOC VARCHAR(13) CONSTRAINT DEPTCONST_LOC_NN2 NOT NULL
);

CREATE TABLE EMP_CONST2(
    EMPNO NUMBER(4) CONSTRAINT EMPCONST_EMPNO_PK2 PRIMARY KEY,
    ENAME VARCHAR(10)CONSTRAINT EMPCONST_ENAME_NN2 NOT NULL,
    JOB VARCHAR(9),
    TEL VARCHAR(20) CONSTRAINT EMPCONST_TEL_UNQ2 UNIQUE,
    HIREDATE DATE,
    SAL NUMBER(7,2) CONSTRAINT EMPCONST_SAL_CHK2 CHECK(SAL BETWEEN 1000 AND 9999),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2) CONSTRAINT EMPCONST_DEPTNO_FK2 REFERENCES DEPT_CONST(DEPTNO)
);

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN('EMP_CONST2','DEPT_CONST2')
    AND TABLE_NAME LIKE '%CONST2';

    

