SELECT *
FROM EMP;

--1번
SELECT *
FROM EMP
WHERE ENAME LIKE '%S';

--2번
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=30 
    AND JOB='SALESMAN';
    
--3번
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE (DEPTNO=20 OR DEPTNO=30) AND SAL>2000;

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO IN(20,30)
    AND SAL>2000;

SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=20 
    AND SAL>2000
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=30 AND SAL>2000;

--4번
SELECT *
FROM EMP
WHERE SAL>=2000
    AND SAL<=3000;
    
SELECT *
FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;
    
SELECT *
FROM EMP
WHERE SAL<2000
    OR SAL>3000;
    
--5번
SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE ENAME LIKE '%E'
    AND DEPTNO=30
    AND SAL NOT BETWEEN 1000 AND 2000;


--6번
SELECT *
FROM EMP
WHERE COMM IS NULL
    AND MGR IS NOT NULL
    AND JOB IN('MANAGER','CLERK')
    AND ENAME NOT LIKE '_L%';
    
SELECT *
FROM EMP;

SELECT EMPNO, ENAME
FROM EMP;

SELECT DISTINCT JOB, deptno
FROM EMP;

SELECT COUNT(DISTINCT JOB)
FROM EMP;

SELECT COUNT(DISTINCT JOB) AS JOBCOUNT
FROM EMP;

SELECT COUNT(*)
FROM EMP;

SELECT *
FROM EMP
WHERE DEPTNO=30;

SELECT *
FROM EMP
WHERE JOB='SALESMAN';

SELECT *
FROM EMP
WHERE JOB='CLERK'
    AND DEPTNO=20;
    
SELECT *
FROM EMP
WHERE JOB='CLERK'
    OR DEPTNO=20;
    
SELECT *
FROM EMP
WHERE NOT JOB='CLERK';

SELECT *
FROM EMP
WHERE JOB='SALESMAN'
    AND NOT DEPTNO=20;
    
SELECT EMPNO, ENAME
FROM EMP
WHERE JOB='SALESMAN'
    AND NOT DEPTNO=20;
    
SELECT *
FROM EMP
WHERE SAL>=(1000*10-100)/10
ORDER BY SAL ASC;

SELECT *
FROM EMP
ORDER BY DEPTNO, HIREDATE;

SELECT *
FROM EMP
ORDER BY DEPTNO DESC, HIREDATE ASC;

SELECT MAX(SAL), MIN(SAL) 
FROM EMP;

SELECT AVG(SAL)
FROM EMP
WHERE JOB='SALESMAN';

SELECT SUM(SAL) 
FROM EMP
WHERE JOB='SALESMAN';

SELECT COUNT(*) AS COUNTNAME
    ,SUM(SAL) AS SUMNAME
    ,AVG(SAL) AS AVGNAME
FROM EMP
WHERE JOB='SALESMAN';

SELECT *
FROM EMP
WHERE DEPTNO IN(10,5,4,20,100);

SELECT *
FROM EMP
WHERE DEPTNO NOT IN(10, 5, 4, 20,100);

SELECT *
FROM EMP
WHERE SAL BETWEEN 1000 AND 2000;

SELECT *
FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 2000;

SELECT *
FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 2000
    AND DEPTNO NOT IN(10,20);
    
SELECT *
FROM EMP
WHERE ENAME BETWEEN 'A' AND 'K';

SELECT *
FROM EMP
WHERE HIREDATE BETWEEN '1981-01-01' AND '1981-06-06';

SELECT *
FROM EMP
WHERE ENAME LIKE 'M%';

SELECT *
FROM EMP
WHERE ENAME LIKE '%M%';

SELECT *
FROM EMP
WHERE ENAME LIKE '%N_%';

SELECT '우리집'||'으로'||'가자'
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYYMMDD')
    ,TO_CHAR(SYSDATE, 'YYYY-MM-DD')
    ,TO_CHAR(SYSDATE, 'YYYY/MM/DD')
    ,TO_CHAR(SYSDATE, 'YYYY')
    ,TO_CHAR(SYSDATE,'MM')
    ,TO_CHAR(SYSDATE,'MON')
    ,TO_CHAR(SYSDATE,'D')
    ,TO_CHAR(SYSDATE,'DD')
    ,TO_CHAR(SYSDATE,'DDD')
    ,TO_CHAR(SYSDATE,'DAY')
    ,TO_CHAR(SYSDATE,'HH24')
    ,TO_CHAR(SYSDATE,'HH:MI:SS')
FROM DUAL;


SELECT *
FROM EMP
WHERE DEPTNO<=20
UNION
SELECT *
FROM EMP
WHERE DEPTNO>=20;

SELECT *
FROM EMP
WHERE DEPTNO<=20
UNION ALL
SELECT *
FROM EMP
WHERE DEPTNO>=20;

SELECT *
FROM EMP
WHERE DEPTNO<=20
MINUS
SELECT *
FROM EMP
WHERE DEPTNO>=20;

SELECT *
FROM EMP
WHERE DEPTNO<=20
INTERSECT
SELECT *
FROM EMP
WHERE DEPTNO>=20;

SELECT *
FROM EMP
WHERE COMM IS NULL;

SELECT *
FROM EMP
WHERE COMM IS NOT NULL;

--P125 5장 Q1
SELECT *
FROM EMP
WHERE ENAME LIKE '%S';

--Q2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=30
    AND JOB='SALESMAN';

--Q3    
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO IN(20, 30)
    AND SAL>2000;
    
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROm EMP
WHERE (DEPTNO=20 OR DEPTNO=30)
    AND SAL>2000;
    
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=20
    AND SAL>2000
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=30
    AND SAL>2000;
    
--Q4    
SELECT *
FROM EMP
WHERE SAL<2000 OR SAL>3000;

SELECT *
FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

--Q5
SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE ENAME LIKE 'J%'
    AND DEPTNO=30
    AND SAL NOT BETWEEN 1000 AND 2000;

--Q6
SELECT *
FROM EMP
WHERE COMM IS NULL
    AND MGR IS NOT NULL
    AND (JOB='MANAGER'
    OR JOB='CLERK')
    AND ENAME NOT LIKE '_L%';
    
SELECT *
FROM EMP
WHERE COMM IS NULL
    AND MGR IS NOT NULL
    AND JOB IN('MANAGER','CLERK')
    AND ENAME NOT LIKE '_L%';    
