--P174 6장 Q1
--EMPNO열
--EMP테이블
--ENAME>=5 <6 사원정보출력
--MASKING_EMPNO 열
--EMPNO 앞 두자리 외* 출력
--MASKING_ENAME 열 사원이름의 첫 글자만 보여주고 나머지 *
SELECT EMPNO
    ,RPAD(SUBSTR(EMPNO,1,2),LENGTH(EMPNO),'*') AS MASKING_EMPNO
    ,ENAME
    ,RPAD(SUBSTR(ENAME,1,1),LENGTH(ENAME),'*') AS MASKING_ENAME
FROM EMP
WHERE LENGTH(ENAME)>=5
    AND LENGTH(ENAME)<6;

SELECT EMPNO
    ,RPAD(SUBSTR(EMPNO,1,2),4,'*') AS MASKING_EMPNO
    ,ENAME
    ,RPAD(SUBSTR(ENAME,1,1),LENGTH(ENAME),'*') AS MASKING_ENAME
FROM EMP
WHERE LENGTH(ENAME)>=5
    AND LENGTH(ENAME)<6;

--Q2
--EMP 테이블
--사원들의 월 평균 근무일 21.5
--하루 근무 시간 8
--하루 급여 DAY_PAY
--시급 TIME_PAY
--단 하루 급여는 소수점 세 번째 자리에서 버리고, 시급은 두 번째 소수점에서 반올림하세요

SELECT EMPNO, ENAME, SAL
    ,TRUNC(SAL/21.5, 2) AS DAY_PAY
    ,ROUND((SAL/21.5)/8,1) AS TIME_PAY
FROM EMP;

SELECT EMPNO,ENAME,SAL
    ,TRUNC(SAL/21.5,2) AS DAY_PAY
    ,ROUND(SAL/21.5/8,1) AS TIME_PAY
FROM EMP;

--Q3
--EMP 테이블
--HIREDATE을 기준으로 3개월이 지난 후 첫 월요일에 정직원이 되는 날짜(R_JOB)를 YYYY-MM-DD 형식 출력
--단 추가 수당(COMM)이 없는 사원이 추가 수당은 N/A로 출력

SELECT EMPNO, ENAME, TO_CHAR(HIREDATE,'YYYY/MM/DD') AS HIREDATE
    , TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3),'월요일'), 'YYYY-MM-DD') AS R_JOB
    , CASE
        WHEN COMM IS NULL THEN 'N/A'
        ELSE TO_CHAR(COMM)
        END AS COMM
FROM EMP;

SELECT EMPNO, ENAME, TO_CHAR(HIREDATE, 'YYYY/MM/DD') AS HIREDATE
    ,TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3),'월요일'), 'YYYY-MM-DD') AS R_JOB
    ,NVL(TO_CHAR(COMM), 'N/A') AS COMM
FROM EMP;
DESC EMP;
--Q4
SELECT EMPNO, 
    ENAME,
--    CASE
--        WHEN MGR IS NULL THEN ' '
--        ELSE TO_CHAR(MGR)
--    END AS MGR,
--NVL(TO_CHAR(MGR),' ') AS MGR,
    NVL2(MGR,TO_CHAR(MGR),' ') AS MGR,    
    CASE
        WHEN MGR IS NULL THEN '0000'
        WHEN SUBSTR(MGR,1,2)=75 THEN '5555'
        WHEN SUBSTR(MGR,1,2)=76 THEN '6666'
        WHEN SUBSTR(MGR,1,2)=77 THEN '7777'
        WHEN SUBSTR(MGR,1,2)=78 THEN '8888'
        ELSE TO_CHAR(MGR) 
    END AS CHG_MGR
FROM EMP;

--지정한 부서번호,부서명,사원이름 및 지정한 사원과 동일한 부서에서 근무하는 모든 사원을
--표시하도록 질의를 작성하고 부서번호는 department, 사원이름은 employee, 동일한
--부서에서 근무하는 사원은 colleague로 표시하시오.
--(부서번호, 사원이름,동료 순으로 오름차순 정렬)

SELECT D.DEPTNO AS department
    , D.DNAME
    , E.ENAME AS employee
    , E.DEPTNO 
    , A.ENAME AS colleague
FROM EMP E, DEPT D, EMP A
WHERE E.DEPTNO=D.DEPTNO
    AND A.DEPTNO=D.DEPTNO
    AND NOT E.ENAME=A.ENAME
ORDER BY department, employee, colleague;

SELECT E1.DEPTNO AS DEPARTMENT
    ,D.DNAME AS DEPARTMENTNAME
    ,E1.ENAME AS EMPLOYEE
    ,E2.DEPTNO
    ,E2.ENAME AS COLLEAGUE
FROM EMP E1, EMP E2, DEPT D
WHERE E1.DEPTNO=E2.DEPTNO
    AND E1.DEPTNO=D.DEPTNO
    AND E1.EMPNO<>E2.EMPNO
ORDER BY DEPARTMENT, EMPLOYEE, COLLEAGUE;

--FROM절 서브쿼리, GROUP BY
SELECT EMPLOYEE AS 사원명, COUNT(COLLEAGUE) AS 동료수
FROM(SELECT E1.DEPTNO AS DEPARTMENT
    ,D.DNAME AS DEPARTMENTNAME
    ,E1.ENAME AS EMPLOYEE
    ,E2.DEPTNO
    ,E2.ENAME AS COLLEAGUE
FROM EMP E1, EMP E2, DEPT D
WHERE E1.DEPTNO=E2.DEPTNO
    AND E1.DEPTNO=D.DEPTNO
    AND E1.EMPNO<>E2.EMPNO
ORDER BY DEPARTMENT, EMPLOYEE, COLLEAGUE
)
GROUP BY EMPLOYEE;