--q1
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE ENAME LIKE '%S';

--Q2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=30
    AND JOB='SALESMAN';
    
--Q3
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO IN(20,30)
    AND SAL>2000;
    
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO=20
    AND SAL>2000
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
FROM EMP
WHERE DEPTNO =30
    AND SAL>2000;
    
    
--Q4
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE SAL<2000
    OR SAL>3000;
    
--Q5
SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE ENAME LIKE '%E%'
    AND DEPTNO=30
    AND SAL NOT BETWEEN 1000 AND 2000;
    
--Q6
SELECT  EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO
FROM EMP
WHERE COMM IS NULL
    AND MGR IS NOT NULL
    AND JOB IN('MANAGER', 'CLERK')
    AND ENAME NOT LIKE '%_L%';


--Q1
SELECT EMPNO
    ,  RPAD(SUBSTR(EMPNO,1,2),LENGTH(EMPNO),'*') AS MASKING_EMPNO
    , ENAME
    , RPAD(SUBSTR(ENAME,1,1),LENGTH(ENAME),'*') AS MASKING_ENAME
FROM  EMP
WHERE LENGTH(ENAME)>=5 AND LENGTH(ENAME)<6;

--Q2
SELECT EMPNO, ENAME, SAL
    , TRUNC(SAL/21.5,2) AS DAY_PAY
    , ROUND(SAL/21.5/8,1) AS TIME_PAY
FROM EMP;

--Q3
SELECT EMPNO, ENAME, HIREDATE
    , NEXT_DAY(ADD_MONTHS(HIREDATE,3),'¿ù¿äÀÏ') AS R_JOB
    , NVL(TO_CHAR(COMM),'N/A')
FROM EMP;

--Q4
SELECT EMPNO, ENAME
    , NVL(TO_CHAR(MGR),' ') MGR
    , CASE
        WHEN MGR IS NULL THEN '0000'
        WHEN SUBSTR(MGR,1,2)=75 THEN '5555'
        WHEN SUBSTR(MGR,1,2)=76 THEN '6666'
        WHEN SUBSTR(MGR,1,2)=77 THEN '7777'
        WHEN SUBSTR(MGR,1,2)=78 THEN '8888'
        ELSE TO_CHAR(MGR)
        END AS CHG_MGR
FROM EMP;

--Q1
SELECT DEPTNO
    , AVG(SAL) AS AVG_SAL
    , MAX(SAL) AS MAX_SAL
    , MIN(SAL) AS MIN_SAL
    , COUNT(SAL) AS CNT
FROM EMP;

--Q2
SELECT JOB, COUNT(*)
FROM EMP
WHERE JOB IS NOT NULL
GROUP BY JOB
HAVING COUNT(JOB)>=3;

--Q3
SELECT TO_CHAR(HIREDATE,'YYYY') AS HIRE_YEAR
    ,DEPTNO
    , COUNT(*) AS CNT
FROM EMP
WHERE DEPTNO IS NOT NULL 
AND TO_CHAR(HIREDATE,'YYYY') IS NOT NULL
GROUP BY TO_CHAR(HIREDATE,'YYYY'),DEPTNO;

--Q4
SELECT NVL2(COMM,'O','X') EXIST_COMM, COUNT(*) CNT
FROM EMP
GROUP BY NVL2(COMM,'O','X');

--Q5
SELECT DEPTNO
    , TO_CHAR(HIREDATE,'YYYY') AS HIRE_YEAR
    , COUNT(*) AS CNT
    , MAX(SAL) AS MAX_SAL
    , AVG(SAL) AS AVG_SAL
FROM EMP
WHERE DEPTNO IS NOT NULL
 AND TO_CHAR(HIREDATE,'YYYY') IS NOT NULL
GROUP BY DEPTNO, TO_CHAR(HIREDATE,'YYYY')
;

--Q1
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
    AND SAL>2000
ORDER BY DEPTNO, SAL;

--Q2
SELECT D.DEPTNO, D.DNAME
    , TRUNC(AVG(E.SAL)) AS AVG_SAL
    , MAX(E.SAL) AS MAX_SAL
    , MIN(E.SAL) AS MIN_SAL
    , COUNT(*) AS CNT
FROM EMP E, DEPT D
WHERE D.DEPTNO=E.DEPTNO
GROUP BY D.DEPTNO, D.DNAME;

--Q3
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
ORDER BY D.DEPTNO, E.ENAME;

--Q4
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL, D.DEPTNO, S.LOSAL, S.HISAL, S.GRADE
    , M.EMPNO AS MGR_EMPNO
    , M.ENAME AS MGR_ENAME
FROM EMP E, DEPT D, SALGRADE S, EMP M
WHERE E.DEPTNO=D.DEPTNO(+)
    AND E.MGR=M.EMPNO(+)
    AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
ORDER BY D.DEPTNO, E.EMPNO;

--Q1
SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME 
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
    AND JOB IN (SELECT JOB
                FROM EMP
                WHERE ENAME='ALLEN');
                
--Q2
SELECT E.EMPNO, E.ENAME, D.DNAME, E.HIREDATE, D.LOC, E.SAL, S.GRADE
FROM EMP E, DEPT D, SALGRADE S
WHERE D.DEPTNO=E.DEPTNO
    AND E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND E.SAL>(SELECT AVG(SAL)
                FROM EMP E)
ORDER BY E.SAL DESC, E.EMPNO;

--Q3
SELECT E.EMPNO, E.ENAME, E.JOB, D.DEPTNO, D.DNAME, D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO
    AND D.DEPTNO=10
    AND JOB NOT IN(SELECT JOB
                    FROM EMP 
                    WHERE DEPTNO=30);

--Q4
SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND SAL>(SELECT DISTINCT MAX(SAL)
            FROM EMP
            WHERE JOB='SALESMAN')
            ORDER BY EMPNO;

SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND SAL >ALL(SELECT DISTINCT SAL
            FROM EMP
            WHERE JOB='SALESMAN')
             ORDER BY EMPNO;

--Q1
CREATE TABLE CH10_EMP AS SELECT * FROM EMP;
CREATE TABLE CH10_DEPT AS SELECT * FROM DEPT;
CREATE TABLE CH10_SAL AS SELECT * FROM SALGRADE;


INSERT INTO CH10_DEPT(DEPTNO, DNAME, LOC)
VALUES (50,'ORACLE','BUSAN');

SELECT *
FROM CH10_DEPT;

DELETE FROM CH10_DEPT WHERE DEPTNO=50;

INSERT ALL
    INTO CH10_DEPT VALUES (60,'SQL','ILSAN')
    INTO CH10_DEPT VALUES (70,'SELECT','INCHEON')
    INTO CH10_DEPT VALUES (80,'DML','BUNDANG')
    SELECT * FROM DUAL;
    
INSERT ALL
    INTO CH10_EMP VALUES (7201,'TEST_USER1','MANAGER',7788,TO_DATE('20160102','YYYY-MM-DD'),4500,NULL,50)
    INTO CH10_EMP VALUES (7202,'TEST_USER2','CLERK',7201,TO_DATE('20160221','YYYY-MM-DD'),1800,NULL,50)
    INTO CH10_EMP VALUES (7203,'TEST_USER3','ANALYST',7201,TO_DATE('20160411','YYYY-MM-DD'),3400,NULL,60)
    INTO CH10_EMP VALUES (7204,'TEST_USER4','SALESMAN',7201,TO_DATE('20160531','YYYY-MM-DD'),2700,300,60)
    INTO CH10_EMP VALUES (7205,'TEST_USER5','CLERK',7201,TO_DATE('20160720','YYYY-MM-DD'),2600,NULL,70)
    INTO CH10_EMP VALUES (7206,'TEST_USER6','CLERK',7201,TO_DATE('20160908','YYYY-MM-DD'),2600,NULL,70)
    INTO CH10_EMP VALUES (7207,'TEST_USER7','LECTURER',7201,TO_DATE('20161028','YYYY-MM-DD'),2300,NULL,80)
    INTO CH10_EMP VALUES (7208,'TEST_USER8','STUDENT',7201,TO_DATE('20180309','YYYY-MM-DD'),1200,NULL,80)
    SELECT * FROM DUAL;

SELECT * FROM CH10_EMP;

UPDATE CH10_EMP
SET DEPTNO=70
WHERE SAL>(SELECT AVG(SAL)
    FROM CH10_EMP
    WHERE DEPTNO=50);
    
SELECT * FROM CH10_EMP
ORDER BY DEPTNO;

--Q4
UPDATE CH10_EMP
SET SAL=SAL*1.1, DEPTNO=80
WHERE HIREDATE>(SELECT MIN(HIREDATE)
        FROM CH10_EMP
        WHERE DEPTNO=60);
--q5
DELETE FROM CH10_EMP 
WHERE EMPNO IN(SELECT E.EMPNO
FROM CH10_EMP E, CH10_SAL S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND S.GRADE=5);
    
--q1
CREATE TABLE EMP_HW(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
);

--Q2
ALTER TABLE EMP_HW
ADD BIGO VARCHAR2(20);
DESC EMP_HW;

--Q3
ALTER TABLE EMP_HW
MODIFY BIGO VARCHAR2(30);

--Q4
ALTER TABLE EMP_HW
RENAME COLUMN BIGO TO REMARK;

--Q5
INSERT INTO EMP_HW
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL
FROM EMP;
SELECT * FROM EMP_HW;

INSERT INTO EMP_HW
SELECT E.*, NULL
FROM EMP E;

INSERT INTO EMP_HW(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
SELECT *
FROM EMP;

--Q12
DROP TABLE EMP_HW;
SELECT * FROM EMP_HW;

--Q13
CREATE TABLE EMPIDX
AS SELECT * FROM EMP;
DROP TABLE EMPIDX;

CREATE INDEX IDX_EMPIDX_EMPNO
ON EMPIDX(EMPNO);

SELECT *
FROM USER_INDEXES
WHERE INDEX_NAME='IDX_EMPIDX_EMPNO';

--Q13
CREATE OR REPLACE VIEW EMPIDX_OVER15K
AS SELECT EMPNO, ENAME,JOB, DEPTNO, SAL, NVL2(TO_CHAR(COMM),'O','X') COMM
FROM EMPIDX
WHERE SAL>1500
;

SELECT * FROM EMPIDX_OVER15K;

CREATE TABLE DEPTSEQ
AS SELECT * FROM DEPT;

DROP TABLE DEPTSEQ;

CREATE SEQUENCE SEQ_DEPTSEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99
    MINVALUE 1
    NOCYCLE
    NOCACHE
    ;
    
DROP SEQUENCE SEQ_DEPTSEQ;
    
INSERT INTO DEPTSEQ(DEPTNO, DNAME, LOC) VALUES (SEQ_DEPTSEQ.NEXTVAL,'DATABASE','SEOUL');
INSERT INTO DEPTSEQ(DEPTNO, DNAME, LOC) VALUES (SEQ_DEPTSEQ.NEXTVAL,'WEB','BUSAN');
INSERT INTO DEPTSEQ(DEPTNO, DNAME, LOC) VALUES (SEQ_DEPTSEQ.NEXTVAL,'MOBILE','ILSAN');

SELECT * FROM DEPTSEQ;


--Q14
CREATE TABLE DEPT_CONST(
    DEPTNO NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR2(14) CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE,
    LOC VARCHAR2(13) CONSTRAINT DEPTCONST_LOC_NN NOT NULL
    );

DROP TABLE DEPT_CONST;
DROP TABLE EMP_CONST;
    
CREATE TABLE EMP_CONST(
    EMPNO NUMBER(4) CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10) CONSTRAINT EMPCONST_ENAME_NN NOT NULL,
    JOB VARCHAR2(9),
    TEL VARCHAR2(20) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
    HIREDATE DATE,
    SAL NUMBER(7,2) CONSTRAINT EMPCONST_SAL_CHK CHECK (SAL BETWEEN 1000 AND 9999),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2) CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST(DEPTNO)
);

SELECT * FROM USER_CONSTRAINTS
WHERE TABLE_NAME IN ('EMP_CONST','DEPT_CONST')
    AND TABLE_NAME LIKE '%CONST';
    

    