CREATE TABLE CH10_EMP AS SELECT *FROM EMP;
CREATE TABLE CH10_DEPT AS SELECT *FROM DEPT;
CREATE TABLE CH10_SAL AS SELECT *FROM SALGRADE;

--Q10-1
INSERT INTO CH10_DEPT(DEPTNO, DNAME, LOC) VALUES(50, 'ORACLE','BUSAN');
INSERT INTO CH10_DEPT(DEPTNO, DNAME, LOC) VALUES(60, 'SQL','ILSAN');

INSERT ALL
    INTO CH10_DEPT VALUES(70,'SELECT','INCHEON')
    INTO CH10_DEPT VALUES(80,'DML','BUNDANG')
    SELECT * FROM DUAL;
    
DELETE FROM CH10_DEPT WHERE DEPTNO=50;
    
SELECT * FROM CH10_DEPT;

DROP TABLE CH10_DEPT;

ALTER TABLE CH10_DEPT
MODIFY DEPTNO NUMBER CONSTRAINT PK_DEPTNO PRIMARY KEY;

--Q10-2
INSERT ALL
    INTO CH10_EMP
    VALUES(7201,'TEST_USER1','MANAGER',7788,TO_DATE('2016-01-02', 'YYYY-MM-DD'),4500,NULL,50)
    INTO CH10_EMP
    VALUES(7202,'TEST_USER2','CLERK',7201,TO_DATE('2016-02-21', 'YYYY-MM-DD'),1800,NULL,50) 
    INTO CH10_EMP
    VALUES(7203,'TEST_USER3','ANALYST',7201,TO_DATE('2016-04-11', 'YYYY-MM-DD'),3400,NULL,60) 
    INTO CH10_EMP
    VALUES(7204,'TEST_USER4','SALESMAN',7201,TO_DATE('2016-05-31', 'YYYY-MM-DD'),2700,300,60) 
    INTO CH10_EMP
    VALUES(7205,'TEST_USER5','CLERK',7201,TO_DATE('2016-07-20', 'YYYY-MM-DD'),2600,NULL,70) 
    INTO CH10_EMP
    VALUES(7206,'TEST_USER6','CLERK',7201,TO_DATE('2016-09-08', 'YYYY-MM-DD'),2600,NULL,70) 
    INTO CH10_EMP
    VALUES(7207,'TEST_USER7','LECTURER',7201,TO_DATE('2016-10-28', 'YYYY-MM-DD'),2300,NULL,80) 
    INTO CH10_EMP
    VALUES(7208,'TEST_USER8','STUDENT',7201,TO_DATE('2018-03-09', 'YYYY-MM-DD'),1200,NULL,80)
SELECT * FROM DUAL;

--Q10-3
SELECT * FROM CH10_EMP;

UPDATE CH10_EMP
SET DEPTNO=70
WHERE SAL>(SELECT AVG(SAL)
            FROM  CH10_EMP
            WHERE DEPTNO=50);

SELECT * FROM CH10_EMP WHERE DEPTNO=70;


--Q10-4
UPDATE CH10_EMP
SET SAL=SAL*1.1, DEPTNO=80
WHERE HIREDATE > (SELECT MIN(HIREDATE)
                FROM CH10_EMP
                WHERE DEPTNO=60);
                
SELECT * FROM CH10_EMP;

--Q10-5
DELETE FROM CH10_EMP
WHERE EMPNO IN(SELECT EMPNO
            FROM CH10_EMP E,CH10_SAL S
            WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                AND S.GRADE=5);
    
SELECT * FROM CH10_EMP;
    
--Q11-1
SELECT * FROM DEPT;
1.DATABAS
2.SEOUL
3.SALES
4.CHICAGO

--Q12-1
CREATE TABLE EMP_HW(
    EMPNO NUMBER(4),
    ENAME VARCHAR(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
);

--Q12-2
ALTER TABLE EMP_HW
ADD BIGO VARCHAR(20);
DESC EMP_HW;
--Q12-3
ALTER TABLE EMP_HW
MODIFY BIGO VARCHAR2(30);

--Q12-4
ALTER TABLE EMP_HW
RENAME COLUMN BIGO TO REMARK;
    
--Q12-5
SELECT * FROM EMP;
INSERT INTO EMP_HW
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO, NULL, NULL
FROM EMP;

SELECT * FROM EMP_HW;    
    
INSERT INTO EMP_HW
SELECT E.*, NULL, NULL
FROM EMP E;

INSERT INTO EMP_HW(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
SELECT *
FROM EMP;

--Q12-6
DROP TABLE EMP_HW;
DESC EMP_HW;

--Q13-1
DROP TABLE EMPIDX;

CREATE TABLE EMPIDX
AS SELECT * FROM EMP;

SELECT * FROM EMPIDX;

CREATE INDEX IDX_EMPIDX_EMPNO
ON EMPIDX(EMPNO);

SELECT * FROM USER_INDEXES
WHERE INDEX_NAME='IDX_EMPIDX_EMPNO';

--Q13-2
CREATE OR REPLACE VIEW EMPIDX_OVER15K
AS SELECT EMPNO, ENAME,JOB,DEPTNO,SAL,NVL2(COMM,'O','X') AS COMM
FROM EMPIDX
WHERE SAL>1500;

SELECT * FROM  EMPIDX_OVER15K;

-Q13-3
DROP TABLE DEPTSEQ;

CREATE TABLE DEPTSEQ
AS SELECT * FROM DEPT;

DROP SEQUENCE SEQ_DEPTSEQ;

CREATE SEQUENCE SEQ_DEPTSEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99
    MINVALUE 1
    NOCYCLE
    NOCACHE;

CREATE SEQUENCE SEQ_DEPTSEQ
    START WITH 60
    INCREMENT BY 10
    MAXVALUE 100
    MINVALUE 10
    NOCYCLE
    NOCACHE;
    
SELECT SEQ_DEPTSEQ.CURRVAL FROM DUAL;
    
INSERT INTO DEPTSEQ(DEPTNO, DNAME, LOC) VALUES (SEQ_DEPTSEQ.NEXTVAL,'DATABASE','SEOUL');
INSERT INTO DEPTSEQ(DEPTNO, DNAME, LOC) VALUES (SEQ_DEPTSEQ.NEXTVAL,'WEB','BUSAN');
INSERT INTO DEPTSEQ(DEPTNO, DNAME, LOC) VALUES (SEQ_DEPTSEQ.NEXTVAL,'MOBILE','ILSAN');

SELECT * FROM DEPTSEQ;

--Q14-1
DROP TABLE DEPT_CONST;

CREATE TABLE DEPT_CONST(
    DEPTNO NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY,
    DNAME VARCHAR2(14) CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE,
    LOC VARCHAR2(13) CONSTRAINT DEPTCONST_LIC_NN NOT NULL
);

CREATE TABLE EMP_CONST(
    EMPNO NUMBER(4) CONSTRAINT DMPCONST_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10) CONSTRAINT EMPCONST_ENAME_NN NOT NULL,
    JOB VARCHAR2(9),
    TEL VARCHAR2(20) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
    HIREDATE DATE,
    SAL NUMBER(7,2) CONSTRAINT EMPCONST_SALI_CHK CHECK(SAL BETWEEN 1000 AND 9999),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2) CONSTRAINT  EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST(DEPTNO)
);

DROP TABLE EMP_CONST;

SELECT * FROM USER_CONSTRAINTS 
WHERE TABLE_NAME IN('EMP_CONST','DEPT_CONST')
    AND TABLE_NAME LIKE '%CONST';

ALTER TABLE EMP_CONST
RENAME CONSTRAINT DMPCONST_EMPNO_PK TO EMPCONST_EMPNO_PK;


    
    