CREATE TABLE TRANSACTION1 (
    CONSUMERID VARCHAR2(20),
    AMOUNT NUMBER);
    
CREATE TABLE TRANSACTION2 (
    CONSUMERID VARCHAR2(20),
    AMOUNT NUMBER);
    
CREATE TABLE TRANSACTION3 (
    CONSUMERID VARCHAR2(20),
    AMOUNT NUMBER);
    
INSERT INTO TRANSACTION1 VALUES('1',100);
INSERT INTO TRANSACTION2 VALUES('1',100);
INSERT INTO TRANSACTION3 VALUES('1',100);