CREATE TABLE EMP_TRIG
AS SELECT * FROM EMP;

CREATE TABLE EMP_LOG(
    TABLENAME VARCHAR2(10), -- DML이 수행된 테이블 이름
    DMP_TYPE VARCHAR2(10), -- DML 명령어의 종류
    EMPNO NUMBER(4), --DML 대상이 된 사원 번호
    USER_NAME VARCHAR2(30), --DML을 수행한 USER 이름
    CHANGE_DATE DATE --DML이 수행된 날짜
);

SELECT * FROM EMP_TRIG;
SELECT * FROM EMP_LOG;

DESC EMP_LOG;

DELETE FROM EMP_TRIG WHERE EMPNO=7703;

INSERT INTO EMP_TRIG
VALUES(9999,'TESTEMP','CLERK',7788,TO_DATE('20220308','YYYYMMDD'),1200,NULL,20);

UPDATE EMP_TRIG SET SAL=1300 WHERE MGR=7788;

DELETE FROM EMP_TRIG WHERE EMPNO=9999;

SELECT * FROM USER_TRIGGERS;

ALTER TRIGGER TRIG1 DISABLE;




