CREATE TABLE MEM(
    MEMNO NUMBER(10) CONSTRAINT MEM_MEMNO_PK PRIMARY KEY,
    MNAME VARCHAR(10),
    MEMPOS VARCHAR(20),
    MADDRESS VARCHAR(1000),
    MEMSHIP VARCHAR(10),
    EFF VARCHAR(20),
    MEMDATE DATE
);

CREATE TABLE COM(
    COMNO NUMBER(10) CONSTRAINT COM_COMNO_PK PRIMARY KEY,
    MEMNO NUMBER(10) CONSTRAINT COM_MEMNO_FK REFERENCES MEM(MEMNO),
    CNAME VARCHAR(10),
    COMPOS VARCHAR(20),
    HOLDOFFICE VARCHAR(10),
    CADDRESS VARCHAR(1000),
    COMTEL VARCHAR(20),
    COMTOB VARCHAR(20)
);

CREATE TABLE CP(
    CPCODE VARCHAR(100),
    CPNAME VARCHAR(20),
    MEMNO NUMBER(10) CONSTRAINT CP_MEMNO_FK REFERENCES MEM(MEMNO)
);

CREATE TABLE SURVEY(
    SURVEYNO NUMBER(10) CONSTRAINT SURVEY_SURVEYNO_PK PRIMARY KEY,
    EVENTNO NUMBER(10) CONSTRAINT SURVEY_EVENTNO_FK REFERENCES EVENT(EVENTNO),
    MEMNO NUMBER(10) CONSTRAINT SURVEY_MEMNO_FK REFERENCES MEM(MEMNO)
    
);

CREATE TABLE EVENT(
    EVENTNO NUMBER(10) CONSTRAINT EVENT_EVENTNO_PK PRIMARY KEY,
    EVENTNAME VARCHAR(10),
    EVENTDATE DATE,
    EVENTDESCIPTION VARCHAR(1000),
    EVENTVENUE VARCHAR(100),
    EVENTEXPENSIVE NUMBER
);

CREATE TABLE FIELD(
    FIELDNO NUMBER(10) CONSTRAINT FIELD_FIELDNO_PK PRIMARY KEY,
    FNAME VARCHAR(10),
    APPLICATIONPROGRAM VARCHAR(100)
);

CREATE TABLE INTERESTFIELD(
    MEMNO NUMBER(10) CONSTRAINT INTERESTFIELD_MEMNO_FK REFERENCES MEM(MEMNO),
    FIELDNO NUMBER(10) CONSTRAINT INTERESTFIELD_FIELDNO_FK REFERENCES FIELD(FIELDNO)
);

CREATE TABLE FEE(
    FEENO NUMBER(10) CONSTRAINT FEE_FEENO_PK PRIMARY KEY,
    FEEDATE DATE,
    AMOUNT NUMBER,
    MEMNO NUMBER(10) CONSTRAINT FEE_MEMNO_FK REFERENCES MEM(MEMNO)
);

CREATE TABLE EVENTPARTICIPATION(
    MEMNO NUMBER(10) CONSTRAINT EVENTPARTICIPATION_MEMNO_FK REFERENCES MEM(MEMNO),
    EVENTNO NUMBER(10) CONSTRAINT EVENTPARTICIPATION_EVENTNO_FK REFERENCES EVENT(EVENTNO)
);

COMMENT ON TABLE MEM IS '회원';

SELECT * FROM USER_TAB_COMMENTS WHERE COMMENTS='회원';

COMMENT ON COLUMN MEM.MEMNO IS '회원번호';
COMMENT ON COLUMN MEM.MNAME IS '회원명';
COMMENT ON COLUMN MEM.MEMPOS IS '모임직위';
COMMENT ON COLUMN MEM.MADDRESS IS '우편주소';
COMMENT ON COLUMN MEM.MEMSHIP IS '회원권';
COMMENT ON COLUMN MEM.EFF IS '유효성';
COMMENT ON COLUMN MEM.MEMDATE IS '가입일';











