/*사용자 생성*/
--CREATE USER [USER NAME] IDENTIFIED BY [PASSWORD]
CREATE USER STUDENT IDENTIFIED BY LOVE;
ALTER USER STU IDENTIFIED BY HOPE;
DROP USER STU;


GRANT CREATE SESSION TO STU;


/*객체권한*/
GRANT SELECT ON SAL_DML TO STU;
GRANT INSERT ON SAL_DML TO STU;

SELECT * FROM SCOTT.SAL_DML;
INSERT INTO SCOTT.SAL_DML VALUES(3, 1000, 2000);


REVOKE SELECT, INSERT ON SAL_DML FROM STU;

SELECT * FROM USER_SYS_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;

CREATE ROLE SCHOOL;
GRANT CONNECT, RESOURCE, CREATE VIEW TO SCHOOL;
GRANT SCHOOL TO STU;

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='SCHOOL';